import mongoose from "mongoose";

const allSchema = new mongoose.Schema(
  {
    orderId: { type: Number, unique: true, required: true, default: "" },
    publicationName: { type: String, default: "" },
    clientName: { type: String, default: "" },
    noOfAds: { type: Number, default: 0 },
    roMultiplyBy: { type: Number, default: 0 },
    qMultiplyBy: { type: Number, default: 0 },
    noOfAds: { type: Number, default: 0 },
    scheme: { type: String, default: "" },
    position: { type: String, default: "" },
    roHeight: { type: Number, default: 0 },
    roWidth: { type: Number, default: 0 },
    qHeight: { type: Number, default: 0 },
    qWidth: { type: Number, default: 0 },
    hui: { type: String, default: "" },
    remark: { type: String, default: "" },
    dateOfInsertion: { type: Date },
    agencyCode: { type: String, default: "" },
    orderRefId: { type: String, default: "" },
    category: { type: String, default: "" },
    code: { type: String, default: "" },
    roRate: { type: Number, default: 0 },
    roDate: { type: Date },
    percentageOfGST: { type: Number, default: 5 },
    agencyCommission1: { type: String, default: "" },
    agencyCommission2: { type: String, default: "" },
    agencyCommission3: { type: String, default: "" },
    totalCommission: { type: Number, default: 0 },
    roAmount: { type: Number, default: 0 },
    roTotalAmount: { type: Number, default: 0 },
    qAmount: { type: Number, default: 0 },
    qTotalAmount: { type: Number, default: 0 },
    address: { type: String, default: "" },
    invoice: { type: String, default: "" },
    pincode: { type: String, default: "" },
    customerId: { type: String, default: "" },
    phone: { type: String, default: "" },
    dueDate: { type: Date },
    referral: { type: String, default: "" },
    qRate: { type: String, default: "" },
    paymentTerms: { type: String, default: "" },
    discount: { type: String, default: "" },
    qDate: { type: Date },
    commonDetailsCompleted: { type: Boolean, default: false },
    releasedOrderDetailsCompleted: { type: Boolean, default: false },
    quotationDetailsCompleted: { type: Boolean, default: false },
    billDate: { type: Date },
    descHeading: { type: String },
    typeOfGST: { type: String, enum: ["CGST+SGST", "IGST"] },
    percentageOfGST: { type: Number },
    billDiscount: { type: Number },
    billDetailsCompleted: { type: Boolean, default: false },
  },
  {
    timestamps: true,
  }
);

const AllModel = mongoose.model("allRoQf", allSchema);

export default AllModel;
